#!/bin/bash
echo "此脚本可将总表分成8张数据表。
请输入日期(yyyy-mm-dd):"
read tradingday
sed s/"curdate()"/"'$tradingday'"/g create.sql > create.tmp;
mysql -uroot -p123456 -Dexchangedata < create.tmp;
rm -rf create.tmp;
mysqldump -uroot -p123456 -t exchangedata cffexquote cffexinterest dcequote dceinterest shfequote shfeinterest czcequote czceinterest >> historydata.sql;
mysql -uroot -p123456 -Dexchangedata < drop.sql;
